### ISSUE TITLE
Batch of comments on portal

### ISSUE THREAD

**Issue by emiliom** [BiG-CZ/BiG-CZ-Portal#3]
cc @aufdenkampe, @lsetiawan 
https://staging.portal.bigcz.org/

- Branding to BiGCZ
  - Change the front-page branding to refer to BiGCZ specifically (not MMW). Start thinking about appropriate logos, instead of just Stround and WikiWatershed
  - Add BiGCZ prefix to the "Critical Zone Data Explorer" application label at upper left
- "Layers:"
  - Add legends ("i" button?) for climate layers.
  - Add mechanism to provide more info (a small popup?) for all layers, including brief descriptions, mention of sources, and links to the originators.
  - Remove all DRB layers
- The first step in the workflow (Get Started vs Open Project buttons) is a bit disorienting. I'll elaborate later
- In the first page, list item # 3 says "Model". But that's not relevant to BiGCZ portal. It should be replaced with the tab used later in the workflow, "Data"
- Change the workflow order so that "Data" (or Search Data) happens before "Analyze". "Search Data is more central in this portal, plus having the Analyze tab first is distracting/disorienting and adds a small processing lag.
- In Select Area:
  - Add a prominent info box or statement warning users about the maximum area of AOI's
  - Remove HUC 8s, since they will always be larger than the maximum AOI area?
  - Remove Congressional and School Districts
  - Some layers are slow to load (eg, HUC 10). Add a "loading" indicator
- Implementation of WDC "variables" controlled vocab (and other parameter, like sample medium), via pre-caching and "staging" (rather than relying on the WDC server catalog API). And/or "free text searching"
- Filter out datasets (specially CINERGI and HydroShare) whose extent (bounding box) is **much** larger than the AOI extent. The extreme case is global-scale datasets
- Status of HydroShare bounding box / spatial searching and results?
- For WDC (and possibly the other catalogs), it'd be helpful to have a "collapsible" (tree?) mechanism to let the user group and collapse results by source/service (eg, for WDC, NWISDV vs NWISUV)
- Add station/result link to source for NWISUV service results, as currently done for NWISDV results
- In the Detailed Views there may be some heterogeneity in labels for link buttons to sources, across catalogs: "Web Services", "Repository", and "Source" *(not sure if that's the name)*

**Comment by lsetiawan** [comment]
Just a couple of addition to @emiliom comments.

- The information popup in detail view is super long. I am thinking maybe add some sort of scroll?

<img width="701" height="500" alt="screen shot 2017-09-20 at 10 49 37" src="https://user-images.githubusercontent.com/17802172/30659966-45432a9a-9df4-11e7-8b72-7dfc4f10e6e6.png">

- Within the detail view, filter is still shown, and when the filter inputs changed, the stuff on the map also changed not only showing the asset in detail. So maybe hide filter bar in detail view?

<img width="952" alt="screen shot 2017-09-20 at 11 13 41" src="https://user-images.githubusercontent.com/17802172/30660160-d1c0c1bc-9df4-11e7-801f-3b5e18f9eb7a.png">

**Comment by emiliom** [comment]
@aufdenkampe, take a look at our comments, above, and let us know (through this issue) what you think on any of them. If there are some comments you agree with and you think they deserve attention soon, we can pass them up to Azavea/Arianna via email or issues on the MMW repo. Thanks.

**Comment by ajrobbins** [comment]
A couple of comments/clarifications:

>For WDC (and possibly the other catalogs), it'd be helpful to have a "collapsible" (tree?) mechanism to let the user group and collapse results by source/service (eg, for WDC, NWISDV vs NWISUV)

I think we could accomodate this neatly in the new filters pane, if it's useful for users to filter by data source.

>Status of HydroShare bounding box / spatial searching and results?

I just checked, and HydroShare release 1.12 was pushed about a month ago. This includes a fix we were waiting for re: bounding box search, so we'll switch to using the production URL instead of the playground one we've been using. We also just ascertained that the HS API is now returning bounding box geometry for every resource, so we are making a card to implement those results in the UI.

>The information popup in detail view is super long.

That's coming directly from the data catalog so we can't change the length, though we could make it scrollable.

**Comment by emiliom** [comment]
Thanks for the follow-ups @ajrobbins! Great to hear that the HydroShare API now supports bounding-box search and response.

>> The information popup in detail view is super long.
>
> That's coming directly from the data catalog so we can't change the length, though we could make it scrollable.

Yeah, we're suggesting the latter -- make the text scrollable so the user is not potentially presented with a large text box by default.

**Comment by emiliom** [comment]
The comments from Don and me at the start of this issue were mostly incremental tweaks and polish, or follow along areas we've already discussed.

Here's **a suggestion for new development,** though based on comments from Anthony it may actually be relatively easy to develop given how portal search results are stored.

It would be very helpful to users to allow a download of the search results into, say, a JSON file. We can discuss what the content of that JSON file should be, but I think the information already harvested i the search should be enough. Anthony agrees that would be very desirable.

If not too onerous (given other priorities), some refactoring of the JSON may be nice, such as downloading as GeoJSON to enable easy map browsing on desktop GIS software, loading in a Jupyter notebook as a GeoPandas GeoDataframe, etc. I realize that likely would lead to some bloat; it's just a thought.

**Comment by emiliom** [comment]
The items in the laundry list of suggestions and comments in this old issue have either been addressed, discarded/discussed, or moved to the new, smaller laundry list at #9 (focused on Monitor My Watershed priorities). So, I'm closing this issue.
