### ISSUE TITLE
ANTHONY: Helping Azavea finish dataset record and details displays

### ISSUE THREAD

**Issue by emiliom** [BiG-CZ/BiG-CZ-Portal#4]
From @aufdenkampe, 9/19:

Hi Emilio,
I just wanted to give you a heads up that Azavea has been cranking way at BiG CZ tasks at double their previous effort (time) in order to spend out all their funding by Nov. 30. As a result, they are making very fast progress on everything we've given them, and they will need additional input by the end of the week as they start their new sprint.

For example, see these issues that are complete or nearly complete:
- WDC / CUAHSI Details View: https://github.com/WikiWatershed/model-my-watershed/pull/2259
- Fetch time series data values from WDC services via WaterML: https://github.com/WikiWatershed/model-my-watershed/issues/2238

So, we need to complete similar work for HydroShare and CINERGI. I'm going try to get one of these done by tomorrow, if possible. I created blanks at [this Google Drive folder](https://drive.google.com/drive/folders/0B_qhslkfooQAcHRnWEI2a1hzOWM​) (note that github is adding the characters "%u200B" to the end of this URL!)

Hopefully you can carve out some time to help out.

**Comment by aufdenkampe** [comment]
Thank you!

**Comment by emiliom** [comment]
**CINERGI** responses and result records were discussed in some detail way back in late May / early June: https://github.com/WikiWatershed/model-my-watershed/issues/1929. Then at a conf call with the CINERGI/SDSC team on July 28 (but we took poor notes).

**Comment by emiliom** [comment]
These task are now being handled directly via MMW issues. Closing.

**Comment by aufdenkampe** [comment]
Listing issues for reference:
https://github.com/WikiWatershed/model-my-watershed/issues/2390
https://github.com/WikiWatershed/model-my-watershed/issues/2391
https://github.com/WikiWatershed/model-my-watershed/issues/2392
https://github.com/WikiWatershed/model-my-watershed/issues/2393
